---
name: Publish a prerelease version of the package to npm
description: This action automates various aspects of publishing a package to the npm registry including running tests, versioning, and tagging.
inputs:
  NPM_TOKEN:
    description: 'The npm token used to publish the package.'
    required: true
  GH_TOKEN:
    description: 'The GitHub access token used to create labels and pull requests.'
    default: ${{ github.token }}
  node-version:
    description: 'The Node.js version to use in the Action'
    required: false
    default: 'lts/*'
  PROVENANCE:
    description: 'Generate provenance statement for the published package.'
    default: 'false'
  NPM_TAG:
    description: 'The npm tag to use when publishing the package.'
    default: 'next'

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: npm

    - name: git config
      shell: bash
      run: |
        git config --global user.name "WordPress VIP Bot"
        git config --global user.email "<22917138+wpcomvip-bot@users.noreply.github.com>"

    - name: Validate & Publish
      shell: bash
      # Must use `github.action_path` since the script is located in a separate checkout than the calling repo.
      # @see https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsrun
      run: ${{ github.action_path }}/bin/publish.sh
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        PROVENANCE: ${{ inputs.PROVENANCE }}
        NPM_TAG: ${{ inputs.NPM_TAG }}
