version: 2

updates:
  - directory: '/'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: '/'
    package-ecosystem: 'npm'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: '/junit-newrelic-processor'
    package-ecosystem: 'docker'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './expose-github-runtime'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './npm-prepare-release'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './npm-publish'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './junit-newrelic-processor'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './dependabot-auto-merge'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './stale'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './changelog'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './npm-publish-prerelease'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './nodejs-setup'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

  - directory: './dependaban'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - '[Status] Needs Review'

