---

name: Stale monitor
description: Autocloses stale issues and pull requests

inputs:
  days-before-stale:
    description: >
      The number of days old an issue or a pull request can be before marking it
      stale. Set to -1 to never mark issues or pull requests as stale
      automatically.
    required: false
    default: '60'
  days-before-close:
    description: >
      The number of days to wait to close an issue or a pull request after it is
      marked stale. Set to -1 to never close stale issues or pull requests.
    required: false
    default: '7'

runs:
  using: "composite"
  steps:
    - name: Process stale issues and pull requests
      uses: actions/stale@main
      id: stale
      with:
        close-issue-label: "[Status] Autoclosed"
        close-pr-label: "[Status] Autoclosed"
        days-before-close: "${{ inputs.days-before-close }}"
        days-before-stale: "${{ inputs.days-before-stale }}"
        exempt-all-milestones: true
        exempt-issue-labels: "[Pri] Critical,[Status] Keep,dependencies"
        exempt-pr-labels: "[Pri] Critical,[Status] Keep,dependencies"
        stale-issue-label: "[Status] Stale"
        stale-issue-message: >
          This issue has been marked stale because it has been open for
          ${{ inputs.days-before-stale }} days with no activity. If there is
          no activity within ${{ inputs.days-before-close }} days, it will be
          closed.


          This is an automation to keep issues manageable and actionable and is
          not a comment on the quality of this issue nor on the work done so
          far. Closed issues are still valuable to the project and are
          available to be searched.
        stale-pr-label: "[Status] Stale"
        stale-pr-message: >
          This pull request has been marked stale because it has been open for
          ${{ inputs.days-before-stale }} days with no activity. If there is
          no activity within ${{ inputs.days-before-close }} days, it will be
          closed.


          This is an automation to keep pull requests manageable and actionable
          and is not a comment on the quality of this pull request nor on the
          work done so far. Closed PRs are still valuable to the project and
          their branches are preserved.
