---
name: Swagger validation
description: This action performs a validation of a Swagger specification. Requires API to be running.

inputs:
  swagger-json-url:
    description: 'Local URL of Swagger Json'
    required: true

runs:
  using: composite
  steps:
    - name: Validate Swagger
      run: node ${{ github.action_path }}/dist/index.mjs '${{ inputs.swagger-json-url }}'
      shell: bash
