---
name: Dependabot auto-merge
description: Merges Dependabot PRs automatically

inputs:
  GITHUB_TOKEN:
    description: Github token - usually available from the variable secrets.GITHUB_TOKEN
    required: true

runs:
  using: 'node16' # GitHub only supports values listed here: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions
  main: 'dist/main.js'
