---

name: Dependabot auto-merge
description: Merges Dependabot PRs automatically

runs:
  using: "composite"
  steps:
    - name: Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1
    - name: Enable auto-merge for Dependabot PRs
      shell: bash
      if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' && github.event.pull_request.user.login == 'dependabot[bot]' }}
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Approve a PR
      shell: bash
      if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' && github.event.pull_request.user.login == 'dependabot[bot]' }}
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
