---

name: Prepare to publish package to npm
description: Creates a pull request that updates version number of the npm package.
inputs:
  NPM_TOKEN:
    description: 'The npm token used to publish the package.'
    required: true
  npm-version-type:
    description: 'The npm version type we are publishing.'
    required: true
    type: choice
    default: 'patch'
    options:
      - patch
      - minor
      - major
  node-version:
    description: 'The Node.js version to use in the Action'
    required: false
    default: 'lts/*'

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org/

    - name: git config
      shell: bash
      run: |
        git config --global user.name "WordPress VIP Bot"
        git config --global user.email "<22917138+wpcomvip-bot@users.noreply.github.com>"

    - name: Validate & Publish
      shell: bash
      # Must use `github.action_path` since the script is located in a separate checkout than the calling repo.
      # @see https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsrun
      run: ${{ github.action_path }}/bin/prepare-release.sh -t ${{ inputs.npm-version-type }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
